function name (firstName: string) {
    return firstName
}
function answers (questionOne: string) {
    answers("Asia")
    return questionOne
}
function checkingStatus (isRight: boolean) {
    if (isRight) {
        scene.setBackgroundColor(7)
        music.baDing.play()
        steveHarvey.sayText("Good" + " " + "Job!", 4000, false)
    } else {
        scene.setBackgroundColor(2)
        info.changeCountdownBy(-5)
        steveHarvey.sayText("Try" + " " + "again", 4000, false)
    }
}
// Don't forget to comment your code as you work!
let answer = 0
let steveHarvey: Sprite = null
info.startCountdown(60)
let firstName = game.askForString("What is your first name?", 12)
scene.setBackgroundColor(1)
steveHarvey = sprites.create(img`
    ........................
    ........................
    ........................
    ....fffffff.............
    ...feeeeeeef............
    ..feffeeffeef...........
    .fefeeeeeefef...........
    .feeefeefeeef...........
    .feeefeefeeeef..........
    feeeefeefeeeeef.........
    .bbbbeefeeeeef..........
    dddddd858ffff...........
    bbbbbb8188feef..........
    bbbbbb8888fdef..........
    .ffff88888feef..........
    ..ffffffff.ff...........
    ....ff..ff..............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
steveHarvey.sayText("Welcome" + " " + name(firstName), 5000, false)
pause(5000)
game.splash(game.askForString("What is the largest continent?"))
if (answer) {
    checkingStatus(true)
} else {
    checkingStatus(false)
}
let puertoRicoFlag = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ........................
    .ffffffffffffffffffffff.
    .f8f222222222222222222f.
    .f88f22222222222222222f.
    .f888ffffffffffffffffff.
    .f8888f111111111111111f.
    .f88188f11111111111111f.
    .f811188fffffffffffffff.
    .f1111188f222222222222f.
    .f8111888ffffffffffffff.
    .f881888f1111111111111f.
    .f88888f11111111111111f.
    .f8888fffffffffffffffff.
    .f888f2222222222222222f.
    .f88f22222222222222222f.
    .ffffffffffffffffffffff.
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
