function name (firstName: string) {
    return firstName
}
function checkingStatus (isRight: boolean) {
    if (isRight) {
        scene.setBackgroundColor(7)
        music.baDing.play()
    } else {
        scene.setBackgroundColor(2)
        info.changeCountdownBy(-5)
    }
}
// Don't forget to comment your code as you work!
let firstName = game.askForString("What is your first name?", 12)
scene.setBackgroundColor(1)
let steveHarvey = sprites.create(img`
    ........................
    ........................
    ........................
    ....fffffff.............
    ...feeeeeeef............
    ..feffeeffeef...........
    .fefeeeeeefef...........
    .feeefeefeeef...........
    .feeefeefeeeef..........
    feeeefeefeeeeef.........
    .bbbbeefeeeeef..........
    dddddd858ffff...........
    bbbbbb8188feef..........
    bbbbbb8888fdef..........
    .ffff88888feef..........
    ..ffffffff.ff...........
    ....ff..ff..............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
steveHarvey.sayText("Welcome" + " " + name(firstName), 5000, false)
pause(5000)
info.startCountdown(60)
game.splash(game.askForString("What is the largest continent?", 12))
let puertoRicoFlag = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ........................
    .ffffffffffffffffffffff.
    .f8f222222222222222222f.
    .f88f22222222222222222f.
    .f888ffffffffffffffffff.
    .f8888f111111111111111f.
    .f88188f11111111111111f.
    .f811188fffffffffffffff.
    .f1111188f222222222222f.
    .f8111888ffffffffffffff.
    .f881888f1111111111111f.
    .f88888f11111111111111f.
    .f8888fffffffffffffffff.
    .f888f2222222222222222f.
    .f88f22222222222222222f.
    .ffffffffffffffffffffff.
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
game.splash(game.askForString("What country has 118 pyramids?", 12))
game.splash(game.askForString("Which animal is known as mans best friend?", 12))
game.splash(game.askForString("Which bird is the symbol of peace?", 12))
game.splash(game.askForString("What s the first three numbers in PI?", 12))
game.splash(game.askForString("What is it called someone who is an expert on math? ", 12))
game.splash(game.askForString("When was the constitution signed?", 12))
game.splash(game.askForString("What year did the twin towers fell?", 12))
game.splash(game.askForString("What is known as thrpowerhouse of cells?", 12))
game.splash(game.askForString("What is the symbol of aluminun in the periodic table? ", 12))
